version: "1.0"
services:
  dlu_ai:
    build: .
    volumes:
      - dlu:/home/node/dist
  nginx:
    image: nginx
    depends_on:
      - dlu_ai
    ports:
      - "80:80"
    volumes:
      - dlu:/var/www/html
      - ./deploy/nginx/nginx.conf:/etc/nginx/nginx.conf
volumes:
  dlu: